import type { ProviderProfile } from "../settings";
import type { ChatMessage } from "../types";

export type SessionModelSource = "override" | "history" | "profile-default";

export interface SessionProfileResolution {
	profile: ProviderProfile;
	modelSource: SessionModelSource;
}

export interface SessionProfileResolutionOptions {
	modelOverrides?: Record<string, string>;
	messages?: ChatMessage[];
	/** Restrict legacy history lookup to responses generated by this agent. */
	historyAgentId?: string;
}

/**
 * Resolve the model used by a profile in one chat session.
 *
 * Explicit tab choices win. For older sessions, the latest applicable
 * assistant message supplies the model before falling back to the profile
 * default. History is read-only; only an explicit override is persisted.
 */
export function resolveSessionProfileWithSource(
	profile: ProviderProfile,
	options: SessionProfileResolutionOptions = {},
): SessionProfileResolution {
	const override = options.modelOverrides?.[profile.id]?.trim();
	if (override) {
		return {
			profile:
				override === profile.model
					? profile
					: { ...profile, model: override },
			modelSource: "override",
		};
	}

	const historyMessage = [...(options.messages ?? [])]
		.reverse()
		.find((message) => {
			if (message.role !== "assistant" || !message.modelName?.trim()) {
				return false;
			}
			if (!options.historyAgentId) return true;
			return (
				message.agentId === options.historyAgentId ||
				message.agentId === profile.id
			);
		});
	const historicalModel = historyMessage?.modelName?.trim();
	if (historicalModel) {
		return {
			profile:
				historicalModel === profile.model
					? profile
					: { ...profile, model: historicalModel },
			modelSource: "history",
		};
	}

	return { profile, modelSource: "profile-default" };
}

/** Resolve the profile as configured for one chat session without mutating credentials. */
export function resolveSessionProfile(
	profile: ProviderProfile,
	modelOverrides?: Record<string, string>,
	messages?: ChatMessage[],
	historyAgentId?: string,
): ProviderProfile {
	return resolveSessionProfileWithSource(profile, {
		modelOverrides,
		messages,
		historyAgentId,
	}).profile;
}
